////////////////////////////////////////////////////////////////////////////////
// File: src/internal/intrinsics.rs
// Description: Intrinsic class definitions
//
// Author: Leon Heidelbach <leon.heidelbach@hhu.de>
// Date: 15.05.2024
//
// License: GPLv3
////////////////////////////////////////////////////////////////////////////////

use std::collections::HashMap;

use crate::internal::{
  ast::Type,
  check::LocalScopeMap,
  tokenize::Keyword,
  types::{BUILTIN_TYPE_ARRAY, BUILTIN_TYPE_STRING},
};

////////////////////////////////////////////////////////////////////////////////
// Intrinsic Subroutines & Builtin Types
////////////////////////////////////////////////////////////////////////////////

lazy_static::lazy_static! {
  pub(crate) static ref INTRINSIC: HashMap<String, LocalScopeMap> = {
    let intrinsics: HashMap<String, LocalScopeMap> = [
      (String::from("Array.new"),
        LocalScopeMap::factory(
          Keyword::Constructor,
          Type::Complex(String::from(BUILTIN_TYPE_ARRAY)),
          vec![Type::Integer],
          1
        )
      ),
      (String::from("Array.dispose"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Void,
          vec![],
          1
        )
      ),
      (String::from("Keyboard.keyPressed"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Character, vec![],
          1
        )
      ),
      (String::from("Keyboard.readChar"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Character,
          vec![],
          1
        )
      ),
      (String::from("Keyboard.readLine"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Complex(String::from(BUILTIN_TYPE_STRING)),
          vec![Type::Complex(String::from(BUILTIN_TYPE_STRING))],
          1
        )
      ),
      (String::from("Keyboard.readInt"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Complex(String::from(BUILTIN_TYPE_STRING))],
          1
        )
      ),
      (String::from("Math.init"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("Math.abs"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer],
          1
        )
      ),
      (String::from("Math.multiply"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer, Type::Integer],
          1
        )
      ),
      (String::from("Math.divide"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer, Type::Integer],
          1
        )
      ),
      (String::from("Math.min"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer, Type::Integer],
          1
        )
      ),
      (String::from("Math.max"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer, Type::Integer],
          1
        )
      ),
      (String::from("Math.sqrt"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer],
          1
        )
      ),
      (String::from("Memory.alloc"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Complex(String::from(BUILTIN_TYPE_ARRAY)),
          vec![Type::Integer],
          1
        )
      ),
      (String::from("Memory.deAlloc"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::AnyComplex],
          0
        )
      ),
      (String::from("Memory.peek"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Integer,
          vec![Type::Integer],
          1
        )
      ),
      (String::from("Memory.poke"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer, Type::Integer],
          0
        )
      ),
      (String::from("Output.moveCursor"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer, Type::Integer],
          0
        )
      ),
      (String::from("Output.printChar"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Character],
          0
        )
      ),
      (String::from("Output.printString"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Complex(String::from(BUILTIN_TYPE_STRING))],
          0
        )
      ),
      (String::from("Output.printInt"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer],
          0
        )
      ),
      (String::from("Output.println"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("Output.backSpace"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("Screen.clearScreen"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("Screen.setColor"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Boolean],
          0
        )
      ),
      (String::from("Screen.drawPixel"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer, Type::Integer],
          0
        )
      ),
      (String::from("Screen.drawLine"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer,
            Type::Integer, Type::Integer, Type::Integer],
          0
        )
      ),
      (String::from("Screen.drawRectangle"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer,
          Type::Integer,Type::Integer,Type::Integer],
          0
        )
      ),
      (String::from("Screen.drawCircle"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer,Type::Integer,Type::Integer],
          0
        )
      ),
      (String::from("String.new"),
        LocalScopeMap::factory(
          Keyword::Constructor,
          Type::Complex(String::from(BUILTIN_TYPE_STRING)),
          vec![Type::Integer],
          1
        )
      ),
      (String::from("String.dispose"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("String.length"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Integer,
          vec![],
          1
        )
      ),
      (String::from("String.charAt"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Character,
          vec![Type::Integer],
          1
        )
      ),
      (String::from("String.setCharAt"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Void,
          vec![Type::Integer, Type::Character],
          0
        )
      ),
      (String::from("String.appendChar"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Complex(String::from(BUILTIN_TYPE_STRING)),
          vec![Type::Character],
          1
        )
      ),
      (String::from("String.eraseLastChar"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("String.intValue"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Integer,
          vec![],
          0
        )
      ),
      (String::from("String.setInt"),
        LocalScopeMap::factory(
          Keyword::Method,
          Type::Void,
          vec![Type::Integer],
          0
        )
      ),
      (String::from("String.backSpace"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Character,
          vec![],
          1
        )
      ),
      (String::from("String.doubleQuote"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Character,
          vec![],
          1
        )
      ),
      (String::from("String.newLine"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Character,
          vec![],
          1
        )
      ),
      (String::from("Sys.halt"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![],
          0
        )
      ),
      (String::from("Sys.error"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer],
          0
        )
      ),
      (String::from("Sys.wait"),
        LocalScopeMap::factory(
          Keyword::Function,
          Type::Void,
          vec![Type::Integer],
          0
        )
      ),
    ].iter().cloned().collect();

    return intrinsics;
  };
}
